semi: false
tabWidth: 2
printWidth: 120
trailingComma: 'none'
singleQuote: true
overrides:
  - files:
      - '*.vue'
    options:
      parser: 'vue'
  - files:
      - '*.js'
    options:
      parser: 'babel'
  - files:
      - '*.yaml'
    options:
      parser: 'yaml'
